Library/Library/urls.py
# from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    # path('admin/', admin.site.urls),
    path('',include("app.urls")),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Library/app/urls.py
from django.urls import path
from app.views import *


app_name="app"
urlpatterns=[
    path("",index,name="index"),
    path("login_page/",login_page,name="login_page"),
    path("login_view/",login_view,name="login_view"),
    path("signup_page/",signup_page,name="signup_page"),
    path('signup_view/',signup_view,name="signup_view"),
    path("logout_view/",logout_view,name="logout_view"),
    path("reset_page/",reset_page,name="reset_page"),
    path("reset_password_view/",reset_password_view,name="reset_password_view"),
    path("book_display/",book_display,name="book_display"),
    path("new_book_page/",new_book_page,name="new_book_page"),
    path("update_page/<slug:slug>",update_page,name="update_page"),
    path("del_page/<slug:slug>/",del_page,name="del_page"),
    path("new_book/",new_book,name="new_book"),
    path("update/<slug:slug>/",update,name="update"),
    path("delete/<slug:slug>/",delete,name="delete"),
    path("issue_page/<slug:slug>/",issue_page,name="issue_page"),
    path("issue/<slug:slug>/",issue,name="issue"),
    path("del_issue/<slug:slug>/",del_issue,name="del_issue"),
    path("del_issue_page/<slug:slug>/",del_issue_page,name="del_issue_page"),
    path("create_data/<num>/",create_data,name="create_data"),
    path("create_data_page/",create_data_page,name="create_data_page"),
    path("update_profile_page/",update_profile_page,name="update_profile_page"),
    path("update_profile/<slug:slug>/",update_profile,name="update_profile"),
    path("staff_page/",staff_page,name="staff_page"),
    path("new_staff_page/",new_staff_page,name="new_staff_page"),
    path("update_staff_page/<slug:slug>/",update_staff_page,name="update_staff_page"),
    path("delete_staff_page/<slug:slug>/",delete_staff_page,name="delete_staff_page"),
    path("new_staff/",new_staff,name="new_staff"),
    path("update_staff/<slug:slug>/",update_staff,name="update_staff"),
    path("delete_staff/<slug:slug>/",delete_staff,name="delete_staff"),


]

Library/app/templates/app/books.html
{%extends 'app/base.html' %}
{%load static%}
{%block head%}
    <header>
      <h1><img src="{%static 'app/img/logo.jpg' %}" style="padding:5px;border-radius:20px;height:60px;"alt="logo"><a href="/">LIBRARY MANAGEMENT SYSTEM</a></h1>
      
      {%if user.is_authenticated %}
      <a id="logout" style="text-decoration: none;color:red;" href="{%url 'app:logout_view'%}">
        <p>({{request.user.username}}) LogOut</p></a>
        <img src="{{request.user.picture.url}}" style="padding:5px;float:right;border-radius:100%;height:60px;"alt="profile_pic">
      <br>
      <input id="search-input" onkeyup="search()" style="padding:10px;font-size:20px;border-radius:10px;height:40px;margin:10px;outline: none;border:solid red 2px;"type="search" placeholder="Search By Code">
      {%if user.is_authenticated and user.is_superuser %}
      <a class="btn-link" style="margin-top:10px;" href="{%url 'app:new_book_page'%}">+New BOOK</a>
      {%endif%}
      </div>
      {%endif%}
      
    </header>
    {%endblock%}
{%block content%}

<table id="my-table">
    <tr>
        <th>ID</th>
        <th>CODE</th>
        <th>NAME</th>
        <th>AUTHOR</th>
        <th>PUBLISHER</th>
        <th>TYPE</th>
        <th>ISSUED</th>
        <th>ISSUE-DATE</th>
        <th>DUE-DATE</th>
        {%if user.is_authenticated and user.is_superuser %}
        <th>UPDATE</th>
        <th>DELETE</th>
        <th>ISSUE</th>
        {%endif%}
      </tr>
    {%for book in books%}
    <tr>
      <td>{{forloop.counter}}</td>
        <td>{{book.code}}</td>
        <td>{{book.name}}</td>
        <td>{{book.author}}</td>
        <td>{{book.publisher}}</td>
        <td>{{book.type}}</td>
        <td>{{book.issued}}</td>
        <td>{{book.issue_date}}</td>
        <td>{{book.due_date}}</td>
        {%if user.is_authenticated and user.is_superuser %}
        <td><a class="btn-link" href="{%url 'app:update_page' book.slug %}">UPDATE</a></td>
        <td><a class="btn-link" href="{%url 'app:del_page' book.slug %}">DELETE</a></td>
        {%if book.issued%}
        <td><a class="btn-link" href="{%url 'app:del_issue_page' book.slug %}">Delete</a></td>
        {%else%}
        <td><a class="btn-link" href="{%url 'app:issue_page' book.slug %}">ISSUE</a></td>
        {%endif%}
        {%endif%}
    </tr>
    {%empty%}
    <tr>
        <td>None</td>
        <td>None</td>
        <td>None</td>
        <td>None</td>
        <td>None</td>
        <td>None</td>
        <td>None</td>
        <td>None</td>
        <td>None</td>
        <td>None</td>
        <td>None</td>
    </tr>

    {%endfor%}              
  </table>
  <script>
  
  function search(){
   let filter=document.getElementById("search-input").value.toUpperCase();
   let tr=document.getElementsByTagName("tr");
   for(var i=0;i<tr.length;i++)
   {
     td=tr[i].getElementsByTagName("td")[1]
     if (td) {
      txtValue = td.textContent || td.innerText;
      if (txtValue.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
   }

   }
  }
  </script>
{%endblock%}

Library/app/templates/app/create.html
{%extends 'app/base.html' %}
{%block content%}
<form action="{%url 'app:new_book' %}" method="post">
    {%csrf_token%}
        <h2>Create New Book </h2><br>
        <label for="code">Book code</label> <input  id="code" type="text" name="code" placeholder="Enter Book code" required>
        <label for="name">Book name</label> <input id="name" type="text"name="name" placeholder="Enter Book Name" required><br><br>
        <label for="author"> Author</label> <input type="text" name="author" placeholder="Enter Author name" required>
        <label for="publisher">Publisher</label> <input type="text" name="publisher" placeholder="Enyer publisher name" required><br><br>
        <label for="Book Type">Book Type</label><select name="type" id="">
        <option value="political">political</option>
        <option value="computer">computer</option>
        <option value="engineering">engineering</option>
        <option value="social">social</option>
        <option value="biological">biological</option>
        <option value="research">research</option>
    </select>
   <input id="slug" onfocus="autoFill()" hidden type="text" name="slug" placeholder="Automatic slug field" readonly required><br><br>

        <button>Submit </button>
        <a class="btn-link" href="{%url 'app:book_display'%}">Cancel</a>
</form>
<script>
function autoFill(){
    code=document.getElementById("code").value;
    name=document.getElementById("name").value;
    data=code+name;
    document.getElementById("slug").value=data;

}

</script>
{%endblock%}

Library/app/templates/app/create_data_page.html
{% extends 'app/base.html' %}
{%load static%}


{%block content%}
<div class="div" style="background-image:url('{%static "app/img/book.jpg" %}');">
    <h1>Confirm for create 10 random books</h1><br><hr><br><br>
    <a class="btn-link" href="{%url 'app:create_data' 11%}">Confirm</a>
    <a class="btn-link" href="{%url 'app:index'%}">Cancel</a>
</div>

{%endblock%}

Library/app/templates/app/del_page.html
{% extends 'app/base.html' %}


{%block content%}
<form action="{%url 'app:delete' book.slug %}" method="post">
    {%csrf_token%}
    <h2>Confirm delete.....!!</h2><br>
    <label for="code">Book code</label><input type="text" name="" readonly value={{book.code}}>
    <label for="name">Book name</label><input type="text" readonly value={{book.name}}><br><br>
    <button type="submit">Delete</button>
    <a class="btn-link" href="{%url 'app:book_display'%}">Cancel</a>
</form>

{%endblock%}

Library/app/templates/app/delete_staff_page.html
{% extends 'app/base.html' %}


{%block content%}
<form action="{%url 'app:delete_staff' user.slug %}" method="post">
    {%csrf_token%}
    <h2>Confirm delete.....!!</h2><br>
    <label  for="username">Username</label> <input readonly type="text" name="username" placeholder="Enter username"value="{{user.username}}" readonly required>
        <label for="email">Email*</label> <input type="email" name="email"value="{{user.email}}" placeholder="Enter Email" required readonly><br><br>
        <label for="phone"> Phone</label> <input readonly type="number" max=10000000000 name="phone" value="{{user.phone}}"placeholder="Enter Phone number" readonlyrequired>
        <label for="admin">Is Admin ?</label>
        <select name="is_admin_status" disabled>
            <option value="False">False</option>
            <option value="True">True</option>
        </select><br><br>
    <button type="submit">Delete</button>
    <a class="btn-link" href="{%url 'app:staff_page'%}">Cancel</a>
</form>

{%endblock%}

Library/app/templates/app/index.html
{%extends 'app/base.html'%}
{%load static%}


{%block content%}
{%if user.is_authenticated and user.is_superuser %}
<div class="div" style="background-image:url('{%static "app/img/book.jpg" %}');">
    <h1>Create Big DATASET</h1><br><hr><br><br>
    <a class="btn-link" href="{%url 'app:create_data_page'%}">Create 10 random books</a>
</div>
<div class="div" style="background-image:url('{%static "app/img/book.jpg" %}');">
    <h1>Manage staff</h1><br><hr><br><br>
    <a class="btn-link" href="{%url 'app:staff_page'%}">PROCEED</a>
</div>
{%endif%}
<div class="div" style="background-image:url('{%static "app/img/book.jpg" %}');">
    <h1>Update My Profile</h1><br><hr><br><br>
    <a class="btn-link" href="{%url 'app:update_profile_page'%}">Update</a>
</div>
<div class="div" style="background-image:url('{%static "app/img/book.jpg" %}');">
    <h1>Explore Books</h1><br><hr><br><br>
    <a class="btn-link" href="{%url 'app:book_display'%}">BOOKS</a>
</div>
{%endblock%}

Library/app/templates/app/issue_page.html
{% extends 'app/base.html' %}


{%block content%}
<form action="{%url 'app:issue' book.slug %}" method="post">
    {%csrf_token%}
    <h2>Issue Page!!</h2><br>
    <label for="code">Book code</label><input type="text" name="" readonly value={{book.code}}>
    <label for="name">Book name</label> <input type="text" readonly value={{book.name}}><br><br>
    <button type="submit">ISSUE BOOK</button>
    <a class="btn-link" href="{%url 'app:book_display'%}">Cancel</a> 
</form>
    
{%endblock%}

Library/app/templates/app/login.html
{% extends 'app/base.html' %}


{%block content%}
<form action="{%url 'app:login_view' %}" method="post">
    {%csrf_token%}
    <h2>User Login</h2><br>
    <label for="username">Username</label> <input type="text" name="username" placeholder="Enter username" required><br><br>
    <label for="password">Password</label> <input type="password" name="password" placeholder="Enter password" required id=""><br><br>
    <button type="submit">Login</button>
    <a class="btn-link" href="{%url 'app:signup_page'%}">SignUp</a>
    <a style="text-decoration:none;float:right;margin-left:20px;" href="{% url 'app:reset_page' %}"> If forgot password ?</a><br>        
</form>
    
{%endblock%}

Library/app/templates/app/new_staff_page.html
{%extends 'app/base.html' %}
{%block content%}
<form enctype="multipart/form-data" action="{%url 'app:new_staff' %}" method="post">
    {%csrf_token%}
        <h2>REGISTER HERE new Staff </h2><br>
        <label for="username">Username</label> <input type="text" id="username" name="username" placeholder="Enter username"id="username" required>
        <label for="email">Email</label> <input onchange="autoFill()" type="email" name="email" placeholder="Enter Email" id="email" required><br><br>
        <label for="password"> Password</label> <input type="password" name="password1" placeholder="Enter password" required>
        <label for="confirm_password"> Confirm Password</label> <input type="password" name="password2" placeholder="Comfirm password" required><br><br>
        <label for="picture">Upload picture</label> <input type="file" name="picture"value="{{request.user.picture.url}}" placeholder="upload profile image" required><br><br>
        <label for="admin">Is Admin ?</label><select name="is_admin_status" value="">
            <option value="False">False</option>
            <option value="True">True</option>
        </select>
        <input id="slug" onfocus="autoFill()" type="text" name="slug" hidden placeholder="Automatic slug field" readonly required><br><br>
        <button>SignUp</button>
        <a class="btn-link" href="{%url 'app:staff_page'%}">Cancel</a>
        <a style="text-decoration:none;float:right;" href="{%url 'app:login_page'%}">If already registred ?</a>
</form>
<script>
    function autoFill(){
         code=document.getElementById("username").value.trim()
        document.getElementById("username").value=code
        name="url_field"
        data=code+name;
        data= data.split(" ").join("")
        document.getElementById("slug").value=data;

    }
    </script>
{%endblock%}

Library/app/templates/app/signup.html
{%extends 'app/base.html' %}
{%block content%}
<form enctype="multipart/form-data" action="{%url 'app:signup_view' %}" method="post">
    {%csrf_token%}
        <h2>REGISTER HERE </h2><br>
        <label for="username">Username</label> <input id="username" type="text" name="username" placeholder="Enter username"id="username" required>
        <label for="email">Email</label> <input onchange="autoFill()" type="email" name="email" placeholder="Enter Email" id="email" required><br><br>
        <label for="password"> Password</label> <input type="password" name="password1" placeholder="Enter password" required>
        <label for="confirm_password"> Confirm Password</label> <input type="password" name="password2" placeholder="Comfirm password" required><br><br>
        <label for="picture">Upload picture</label> <input type="file" name="picture"value="{{request.user.picture.url}}" placeholder="upload profile image" required><br><br>
        <input id="slug"  type="text" name="slug" hidden placeholder="Automatic slug field" readonly required><br><br>
        <button>SignUp</button>
        <a style="text-decoration:none;float:right;" href="{%url 'app:login_page'%}">If already registred ?</a>
</form>
<script>
    function autoFill(){
        code=document.getElementById("username").value.trim()
        document.getElementById("username").value=code
        name="url_field"
        data=code+name;
        data= data.split(" ").join("")
        document.getElementById("slug").value=data;

    }
    </script>
{%endblock%}

Library/app/templates/app/staff.html
{%extends 'app/base.html' %}
{%load static%}
{%block head%}
    <header>
      <h1><img src="{%static 'app/img/logo.jpg' %}" style="padding:5px;border-radius:20px;height:60px;"alt="logo"><a href="/">LIBRARY MANAGEMENT SYSTEM</a></h1>
      
      {%if user.is_authenticated %}
      <a id="logout" style="text-decoration: none;color:red;" href="{%url 'app:logout_view'%}">
        <p>({{request.user.username}}) LogOut</p></a>
        <img src="{{request.user.picture.url}}" style="padding:5px;float:right;border-radius:100%;height:60px;"alt="profile_pic">
      <br>
      <input id="search-input" onkeyup="search()" style="padding:10px;font-size:20px;border-radius:10px;height:40px;margin:10px;outline: none;border:solid red 2px;"type="search" placeholder="Search By username">
      {%if user.is_authenticated and user.is_superuser %}
      <a class="btn-link" style="margin-top:10px;" href="{%url 'app:new_staff_page'%}">+New STAFF</a>
      {%endif%}
      </div>
      {%endif%}
      
    </header>
    {%endblock%}
{%block content%}

<table id="my-table">
    <tr>
        <th>ID</th>
        <th>USERNAME</th>
        <th>EMAIL</th>
        <th>IMAGE</th>
        <th>PHONE</th>
        <th>IS_ADMIN</th>
        <th>LAST_LOGIN</th>
        {%if user.is_authenticated and user.is_superuser %}
        <th>UPDATE</th>
        <th>DELETE</th>
        {%endif%}
      </tr>
    {%for user in users%}
    <tr>
      <td>{{forloop.counter}}</td>
        <td>{{user.username}}</td>
        <td>{{user.email}}</td>
        <td><a href="{{user.picture.url}}"><img src="{{user.picture.url}}" height="25" width="25" alt="img"></a></td></a>
        <td>{{user.phone}}</td>
        <td>{{user.is_superuser}}</td>
        <td>{{user.last_login}}</td>
        <td><a class="btn-link" href="{%url 'app:update_staff_page' user.slug %}">UPDATE</a></td>
        <td><a class="btn-link" href="{%url 'app:delete_staff_page' user.slug %}">DELETE</a></td>
    </tr>
    {%empty%}
    <tr>
        <td>None</td>
        <td>None</td>
        <td>None</td>
        <td>None</td>
        <td>None</td>
        <td>None</td>
        <td>None</td>
        <td>None</td> 
        <td>None</td>   </tr>

    {%endfor%}              
  </table>
  <script>
  
  function search(){
   let filter=document.getElementById("search-input").value.toUpperCase();
   let tr=document.getElementsByTagName("tr");
   for(var i=0;i<tr.length;i++)
   {
     td=tr[i].getElementsByTagName("td")[1]
     if (td) {
      txtValue = td.textContent || td.innerText;
      if (txtValue.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
   }

   }
  }
  </script>
{%endblock%}

Library/app/templates/app/update.html
{%extends 'app/base.html' %}
{%block content%}
<form action="{%url 'app:update' book.slug %}" method="post">
    {%csrf_token%}
        <h2>Update Book </h2><br>
        <label for="code">Book code</label> <input type="text" name="code" placeholder="Enter Book code" value="{{book.code}}" required>
        <label for="name">Book name</label> <input type="text"name="name" placeholder="Enter Book Name" value="{{book.name}}"required><br><br>
        <label for="author"> Author</label> <input type="text" value="{{book.author}}" name="author" placeholder="Enter Author name" required>
        <label for="publisher">Publisher</label> <input type="text" name="publisher" placeholder="Enyer publisher name" value="{{book.publisher}}"required><br><br>
        <label for="Book Type">Book Type</label>
        <select name="type"value="{{book.type}}" id="" required>
        <option value="political">political</option>
        <option value="computer">computer</option>
        <option value="engineering">engineering</option>
        <option value="social">social</option>
        <option value="biological">biological</option>
        <option value="research">research</option>
    </select>
        <button>Update</button>
        <a class="btn-link" href="{%url 'app:book_display'%}">Cancel</a> 
</form>
{%endblock%}

Library/app/templates/app/update_profile_page.html
{%extends 'app/base.html' %}
{%block content%}
<form enctype="multipart/form-data" action="{%url 'app:update_profile' request.user.slug%}" method="post">
    {%csrf_token%}
        <h2>Update Profile </h2><br>
        <label  for="username">Username</label> <input readonly type="text" name="username" placeholder="Enter username"value="{{request.user.username}}" required>
        <label for="email">Email*</label> <input type="email" name="email"value="{{request.user.email}}" placeholder="Enter Email" required><br><br>
        <label for="phone"> Phone</label> <input type="number" max=10000000000 name="phone" value="{{request.user.phone}}"placeholder="Enter Phone number" required>
        <label for="picture">Upload picture</label> <input type="file" name="picture" title="{{request.user.picture.url}}" placeholder="upload profile image" required><br><br>
        <label for="address">Address</label><br><br><textarea name="address"  cols="30" rows="4" placeholder="Enter address" style="padding:5px;margin:10px;border:solid 2px black;"></textarea><br><br>
        <button>UPDATE</button><a class="btn-link" href="{%url 'app:staff_page'%}">Cancel</a>
        <a style="text-decoration:none;float:right;" href="{%url 'app:login_page'  %}">If already registred ?</a>
</form>
{%endblock%}

Library/app/templates/app/update_staff_page.html
{%extends 'app/base.html' %}
{%block content%}
<form enctype="multipart/form-data" action="{%url 'app:update_staff' user.slug%}" method="post">
    {%csrf_token%}
        <h2>Update STAFF</h2><br>
        <label  for="username">Username</label> <input readonly type="text" name="username" placeholder="Enter username"value="{{user.username}}" required>
        <label for="email">Email*</label> <input type="email" name="email"value="{{user.email}}" placeholder="Enter Email" required><br><br>
        <label for="phone"> Phone</label> <input type="number" max=10000000000 name="phone" value="{{user.phone}}"placeholder="Enter Phone number" required>
        <label for="admin">Is Admin ?</label>
        <select name="is_admin_status" value="">
            <option value="False">False</option>
            <option value="True">True</option>
        </select><br><br>
        <label for="picture">Upload picture</label> <input type="file" name="picture" value="{{user.picture.url}}" title="{{user.picture.url}}" placeholder="upload profile image" required><br><br>

        <label for="address">Address</label><br><br><textarea name="address"  cols="30" rows="4"  placeholder="Enter address" style="padding:5px;margin:10px;border:solid 2px black;">{{user.address}}</textarea><br><br>
        <button>UPDATE</button><a class="btn-link" href="{%url 'app:staff_page'%}">Cancel</a>
        <a style="text-decoration:none;float:right;" href="{%url 'app:login_page'  %}">If already registred ?</a>
</form>

{%endblock%}